# Generated by Django 4.0.4 on 2022-10-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_order', '0002_order_j_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
