# Generated by Django 4.0.4 on 2022-10-20 08:17

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_order', '0003_alter_order_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='j_payment_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ پرداخت شمسی'),
        ),
    ]
