# Generated by Django 4.0.4 on 2022-10-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_order', '0004_alter_order_j_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='j_payment_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
