# Generated by Django 4.1.7 on 2023-05-26 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_order', '0010_alter_order_j_payment_date_alter_order_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='codeFolowed',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{25}$')], verbose_name='کد رهگیری'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='ارسال شده/نشده'),
        ),
    ]
