# Generated by Django 4.1.7 on 2023-05-26 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_order', '0011_order_codefolowed_order_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='codeFolowed',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{25}$')], verbose_name='کد رهگیری'),
        ),
    ]
