# Generated by Django 4.1.7 on 2023-10-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codeVarifySms',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='کد تایید پیامکی'),
        ),
    ]
