# Generated by Django 4.1.7 on 2023-10-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_account', '0003_user_codevarifysms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمی2ل'),
        ),
    ]
