# Generated by Django 4.1.7 on 2023-10-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spad_account', '0004_user_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email2',
        ),
    ]
