# Generated by Django 4.0.4 on 2023-02-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='هزینه ارسال ')),
                ('price', models.IntegerField(verbose_name='هزینه ی پست')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'هزینه ارسال',
            },
        ),
    ]
