# Generated by Django 4.1.7 on 2023-03-01 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150, verbose_name='نام')),
                ('lastName', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('country', models.CharField(choices=[('iran', 'ایران')], default='iran', max_length=20)),
                ('city', models.CharField(max_length=150, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0999999999'. Up to 15 digits allowed.", regex='^\\0?1?\\d{9,15}$')], verbose_name='تلفن ثابت')),
                ('mobile_phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0999999999'. Up to 15 digits allowed.", regex='^\\0?1?\\d{9,15}$')], verbose_name='تلفن همراه')),
                ('post_code', models.TextField(verbose_name='کد پستی')),
            ],
        ),
    ]
