# Generated by Django 4.1.7 on 2023-03-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0002_postadress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostAdress',
            new_name='PostAddress',
        ),
    ]
