# Generated by Django 4.1.7 on 2023-03-01 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_information', '0003_rename_postadress_postaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postaddress',
            options={'verbose_name': 'اطلاعات پست', 'verbose_name_plural': 'اطلاعات پست'},
        ),
        migrations.AddField(
            model_name='postaddress',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postaddress',
            name='country',
            field=models.CharField(choices=[('iran', 'ایران')], default='iran', max_length=20, verbose_name='کشور'),
        ),
    ]
