# Generated by Django 4.1.7 on 2023-03-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0004_alter_postaddress_options_postaddress_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaddress',
            name='post_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),
    ]
