# Generated by Django 4.1.7 on 2023-03-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0005_alter_postaddress_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAddressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isResive', models.BooleanField(default=False)),
                ('addressSelected', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post_information.postaddress', verbose_name=' آدرس انتخابی ')),
            ],
        ),
    ]
