# Generated by Django 4.1.7 on 2023-03-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0007_alter_postaddressdetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postaddressdetail',
            name='OrderDetailSelected',
        ),
    ]
