# Generated by Django 4.1.7 on 2023-03-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0009_alter_postaddressdetail_addressselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaddressdetail',
            name='addressSelected',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post_information.postaddress', verbose_name=' آدرس انتخابی '),
        ),
    ]
