# Generated by Django 4.1.7 on 2023-03-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_order', '0009_order_j_payment_date_alter_order_payment_date'),
        ('post_information', '0010_alter_postaddressdetail_addressselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaddressdetail',
            name='OrderDetailSelected',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='spad_eshop_order.orderdetail', verbose_name=' سبد خرید انتخابی انتخابی '),
            preserve_default=False,
        ),
    ]
