# Generated by Django 4.1.7 on 2023-05-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0014_alter_postaddressdetail_addressselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaddress',
            name='mobile_phone_number',
            field=models.CharField(max_length=17, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='postaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, verbose_name='تلفن ثابت'),
        ),
    ]
