# Generated by Django 4.1.7 on 2023-05-14 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0015_alter_postaddress_mobile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaddress',
            name='mobile_phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0999999999'. Up to 15 digits allowed.", regex='^\\0?1?\\d{9,15}$')], verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='postaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0999999999'. Up to 15 digits allowed.", regex='^\\0?1?\\d{9,15}$')], verbose_name='تلفن ثابت'),
        ),
    ]
