# Generated by Django 4.1.7 on 2023-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0018_alter_postaddressdetail_carrierdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaddressdetail',
            name='carrierDetails',
            field=models.CharField(choices=[('1', 'پست'), ('2', 'تیپاکس'), ('3', 'باربری')], default='پست', max_length=20, verbose_name='روش ارسال'),
        ),
    ]
