# Generated by Django 4.1.7 on 2023-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0019_alter_postaddressdetail_carrierdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaddressdetail',
            name='carrierDetails',
            field=models.CharField(choices=[('1', 'پست'), ('2', 'تیپاکس'), ('3', 'باربری')], default=1, max_length=20, verbose_name='روش ارسال'),
        ),
    ]
