# Generated by Django 4.1.7 on 2023-06-09 17:03

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0020_alter_postaddressdetail_carrierdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaddressdetail',
            name='Ongoing',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ در دست اقدام'),
        ),
        migrations.AddField(
            model_name='postaddressdetail',
            name='carried',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ حمل شده'),
        ),
        migrations.AddField(
            model_name='postaddressdetail',
            name='collected',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ جمع آوری شده'),
        ),
        migrations.AddField(
            model_name='postaddressdetail',
            name='collecting',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ در حال جمع اوری'),
        ),
        migrations.AddField(
            model_name='postaddressdetail',
            name='confirmedPayment',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت تایید شده'),
        ),
        migrations.AddField(
            model_name='postaddressdetail',
            name='processing',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ در حال پردازش'),
        ),
        migrations.AddField(
            model_name='postaddressdetail',
            name='sentToShippingUnit',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال شده به واحد حمل'),
        ),
    ]
