# Generated by Django 4.1.7 on 2023-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0021_postaddressdetail_ongoing_postaddressdetail_carried_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaddress',
            name='isCorrect_mobile_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
