# Generated by Django 4.1.7 on 2023-07-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0024_alter_paymentmethodedetail_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodedetail',
            name='isTermsAndRules',
            field=models.BooleanField(default=False),
        ),
    ]
