# Generated by Django 4.1.7 on 2023-07-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0025_paymentmethodedetail_istermsandrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodedetail',
            name='TermsAndRules_field',
            field=models.TextField(blank=True, null=True, verbose_name=' شرایط '),
        ),
        migrations.AlterField(
            model_name='paymentmethodedetail',
            name='isTermsAndRules',
            field=models.BooleanField(default=False, verbose_name=' پذیرفتن شرایط '),
        ),
    ]
