# Generated by Django 4.1.7 on 2023-07-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_order', '0012_alter_order_codefolowed'),
        ('post_information', '0027_alter_paymentmethodedetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodedetail',
            name='OrderDetailSelected',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='spad_eshop_order.order', verbose_name=' سبد خرید انتخابی انتخابی '),
            preserve_default=False,
        ),
    ]
