# Generated by Django 4.1.7 on 2023-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0028_paymentmethodedetail_orderdetailselected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethodedetail',
            options={'verbose_name': 'جزئیات پرداخت', 'verbose_name_plural': 'جرئیات پرداخت'},
        ),
        migrations.AddField(
            model_name='paymentmethodedetail',
            name='peymentCode',
            field=models.CharField(default=1, max_length=150, verbose_name=' کد پرداخت '),
            preserve_default=False,
        ),
    ]
