# Generated by Django 4.1.7 on 2023-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0029_alter_paymentmethodedetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodedetail',
            name='peymentCode',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' کد پرداخت '),
        ),
    ]
