# Generated by Django 4.1.7 on 2023-08-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_order', '0013_order_payment_tracking_number'),
        ('post_information', '0030_alter_paymentmethodedetail_peymentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaddressdetail',
            name='OrderDetailSelected',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spad_eshop_order.order', verbose_name=' سبد خرید انتخابی  '),
        ),
    ]
