# Generated by Django 4.1.7 on 2023-08-11 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0032_paymentmethodedetail_payment_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethodedetail',
            name='payment_tracking_number',
        ),
        migrations.AlterField(
            model_name='paymentmethodedetail',
            name='peymentCode',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{25}$')], verbose_name=' کد پرداخت '),
        ),
    ]
