# Generated by Django 4.1.7 on 2023-07-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='TermsAndRules_field',
            field=models.TextField(blank=True, null=True, verbose_name=' شرایط '),
        ),
    ]
