# Generated by Django 4.0.4 on 2022-09-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='priceOff',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف'),
        ),
    ]
