# Generated by Django 4.0.4 on 2022-10-11 16:06

from django.db import migrations
import django_resized.forms
import spad_eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_products', '0004_alter_product_image_tumpnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_tumpnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[150, 100], upload_to=spad_eshop_products.models.upload_image_tumpnail_path, verbose_name='تصویر_بند_انگشتی'),
        ),
    ]
