# Generated by Django 4.0.4 on 2022-10-11 16:16

from django.db import migrations, models
import spad_eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('spad_eshop_products', '0005_alter_product_image_tumpnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_tumpnail',
            field=models.ImageField(blank=True, null=True, upload_to=spad_eshop_products.models.upload_image_tumpnail_path, verbose_name='تصویر_بند_انگشتی'),
        ),
    ]
